block-beta
  columns 8

  %% --- ENCABEZADOS DE DOMINIO ---
  c_crm["<b>CRM / SRM</b>"]
  c_srv["<b>Service</b>"]
  c_sal["<b>Sales</b>"]
  c_pur["<b>Purchasing</b>"]
  c_inv["<b>Inventory</b>"]
  c_prd["<b>Production</b>"]
  c_fin["<b>Finance</b>"]
  c_rep["<b>Reporting</b>"]

  %% --- NIVEL 1: MASTER DATA & INICIACIÓN ---
  bp_act["Activities"]
  srv_cec["Customer Equip. Card"]
  sal_opp["Opportunity"]
  pur_req["Purchase Request"]
  inv_itm["Item Master"]
  prd_bom["Bill of Materials"]
  fin_coa["Chart of Accounts"]
  space

  %% --- NIVEL 2: PLANIFICACIÓN & PRECIOS ---
  bp_cus["Customer"]
  srv_cal["Service Call"]
  sal_prc["Pricing"]
  pur_quo["Purchase Quotation"]
  inv_whm["Warehouse Mgmt"]
  prd_mrp["MRP"]
  fin_gla["General Ledger"]
  space

  %% --- NIVEL 3: COTIZACIONES & DEMANDA ---
  bp_led["Lead"]
  srv_cnt["Service Contract"]
  sal_quo["Sales Quotation"]
  space
  inv_dmd["Demand Planning"]
  prd_src["Sourcing"]
  fin_gld["G/L Determination"]
  rep_bor["Backorder Report"]

  %% --- NIVEL 4: ÓRDENES ACTIVAS ---
  bp_sup["Supplier"]
  srv_bil["Service Billing"]
  sal_ord["Sales Order"]
  pur_ord["Purchase Order"]
  space
  prd_ord["Production Order"]
  fin_cst["Cost Accounting"]
  space

  %% --- NIVEL 5: MOVIMIENTOS DE ALMACÉN / EJECUCIÓN ---
  bp_bpm["BP Master"]
  space
  sal_del["Delivery Note"]
  pur_grp["Goods Receipt PO"]
  space
  prd_iss["Issue to Production"]
  fin_iar["Inventory Audit"]
  space

  %% --- NIVEL 6: FACTURACIÓN & REGISTRO CONTABLE ---
  space
  space
  sal_ari["AR Invoice"]
  pur_api["AP Invoice"]
  space
  prd_rec["Receipt from Prod."]
  fin_jne["Journal Entries"]
  rep_abr["Account Balances"]

  %% --- NIVEL 7: PAGOS & TESORERÍA ---
  space
  space
  sal_inc["Incoming Payments"]
  pur_out["Outgoing Payments"]
  space
  space
  fin_apa["AP / AR & Cash Mgmt"]
  rep_pdr["Product Reporting"]

  %% --- NIVEL 8: CIERRE & REPORTES FINALES ---
  space
  space
  space
  space
  space
  space
  fin_rec["Reconciliation"]
  rep_fnr["Financial Reporting"]

  %% --- CONEXIONES VERTICALES PRINCIPALES ---
  bp_act --> bp_cus --> bp_led --> bp_sup --> bp_bpm
  srv_cec --> srv_cal --> srv_cnt --> srv_bil
  sal_opp --> sal_prc --> sal_quo --> sal_ord --> sal_del --> sal_ari --> sal_inc
  pur_req --> pur_quo --> pur_ord --> pur_grp --> pur_api --> pur_out
  inv_itm --> inv_whm --> inv_dmd
  prd_bom --> prd_mrp --> prd_src --> prd_ord --> prd_iss --> prd_rec
  fin_coa --> fin_gla --> fin_gld --> fin_cst --> fin_iar --> fin_jne --> fin_apa --> fin_rec
  rep_bor --> rep_abr --> rep_pdr --> rep_fnr

  %% --- INTEGRACIONES MULTI-ÁREA CLAVE ---
  sal_del --> fin_jne
  pur_grp --> fin_jne
  sal_ari --> fin_apa
  pur_api --> fin_apa
  fin_rec --> rep_fnr
  prd_rec --> rep_pdr
